name: bot-request-site

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080" 
    env_file:
      - ./backend/.env
    depends_on:
      - database
  
  database:
    image: postgres:18.6
    ports:
    - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    env_file:
      - ./.env

volumes:
  pgdata: