// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: approve_tag_alias.sql

package database

import (
	"context"
)

const approveTagAlias = `-- name: ApproveTagAlias :one
UPDATE tag_aliases
SET alias_status = 'approved'
WHERE id = $1
RETURNING id, name, tag_id, created_at, alias_status
`

func (q *Queries) ApproveTagAlias(ctx context.Context, id int64) (TagAlias, error) {
	row := q.db.QueryRowContext(ctx, approveTagAlias, id)
	var i TagAlias
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TagID,
		&i.CreatedAt,
		&i.AliasStatus,
	)
	return i, err
}
