// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: change_request_status.sql

package database

import (
	"context"
)

const changeRequestStatus = `-- name: ChangeRequestStatus :one
UPDATE requests
SET status = $1
WHERE id = $2
RETURNING id, created_at, updated_at, request_text, status, request_search_vector
`

type ChangeRequestStatusParams struct {
	Status RequestStatus
	ID     int64
}

func (q *Queries) ChangeRequestStatus(ctx context.Context, arg ChangeRequestStatusParams) (Request, error) {
	row := q.db.QueryRowContext(ctx, changeRequestStatus, arg.Status, arg.ID)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RequestText,
		&i.Status,
		&i.RequestSearchVector,
	)
	return i, err
}
