// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: change_fulfilled_claims_to_expired.sql

package database

import (
	"context"
)

const changeFulfilledClaimExpireTimes = `-- name: ChangeFulfilledClaimExpireTimes :exec
UPDATE request_claims AS claim
SET expires_at = NOW()
FROM requests AS request
WHERE request.id = claim.request_id AND request.status IN ('fulfilled', 'cancelled')
`

func (q *Queries) ChangeFulfilledClaimExpireTimes(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, changeFulfilledClaimExpireTimes)
	return err
}
