// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: create_request.sql

package database

import (
	"context"
)

const createRequest = `-- name: CreateRequest :one
INSERT INTO requests(created_at, updated_at, request_text)
VALUES(NOW(), NOW(), $1)
RETURNING id, created_at, updated_at, request_text
`

func (q *Queries) CreateRequest(ctx context.Context, requestText string) (Request, error) {
	row := q.db.QueryRowContext(ctx, createRequest, requestText)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RequestText,
	)
	return i, err
}
