// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: create_tag_alias.sql

package database

import (
	"context"
	"database/sql"
)

const createTagAlias = `-- name: CreateTagAlias :one
INSERT INTO tag_aliases(name, tag_id, created_at)
VALUES($1, $2, NOW())
RETURNING id, name, tag_id, created_at, alias_status
`

type CreateTagAliasParams struct {
	Name  string
	TagID sql.NullInt64
}

func (q *Queries) CreateTagAlias(ctx context.Context, arg CreateTagAliasParams) (TagAlias, error) {
	row := q.db.QueryRowContext(ctx, createTagAlias, arg.Name, arg.TagID)
	var i TagAlias
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TagID,
		&i.CreatedAt,
		&i.AliasStatus,
	)
	return i, err
}
