// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: create_request_tag_link.sql

package database

import (
	"context"
)

const createRequestTagLink = `-- name: CreateRequestTagLink :one
INSERT INTO request_tags(request_id, tag_id)
VALUES ($1, $2)
RETURNING request_id, tag_id
`

type CreateRequestTagLinkParams struct {
	RequestID int64
	TagID     int64
}

func (q *Queries) CreateRequestTagLink(ctx context.Context, arg CreateRequestTagLinkParams) (RequestTag, error) {
	row := q.db.QueryRowContext(ctx, createRequestTagLink, arg.RequestID, arg.TagID)
	var i RequestTag
	err := row.Scan(&i.RequestID, &i.TagID)
	return i, err
}
