// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: create_request_claim.sql

package database

import (
	"context"
)

const createRequestClaim = `-- name: CreateRequestClaim :one
INSERT INTO request_claims(request_id, claimed_at, claim_secret_hash, expires_at)
VALUES($1, NOW(), $2, NOW() + INTERVAL '30 days')
RETURNING request_id, claimed_at, claim_secret_hash, expires_at
`

type CreateRequestClaimParams struct {
	RequestID       int64
	ClaimSecretHash string
}

func (q *Queries) CreateRequestClaim(ctx context.Context, arg CreateRequestClaimParams) (RequestClaim, error) {
	row := q.db.QueryRowContext(ctx, createRequestClaim, arg.RequestID, arg.ClaimSecretHash)
	var i RequestClaim
	err := row.Scan(
		&i.RequestID,
		&i.ClaimedAt,
		&i.ClaimSecretHash,
		&i.ExpiresAt,
	)
	return i, err
}
