// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: create_tag.sql

package database

import (
	"context"
)

const createTag = `-- name: CreateTag :one
INSERT INTO tags(tag_name, created_at, updated_at)
VALUES($1, NOW(), NOW())
RETURNING id, tag_name, created_at, updated_at
`

func (q *Queries) CreateTag(ctx context.Context, tagName string) (Tag, error) {
	row := q.db.QueryRowContext(ctx, createTag, tagName)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.TagName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
