// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: delete_tag_by_id.sql

package database

import (
	"context"
)

const deleteTagById = `-- name: DeleteTagById :exec
DELETE FROM tags
WHERE id = $1
`

func (q *Queries) DeleteTagById(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTagById, id)
	return err
}
