// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: delete_tag_by_name.sql

package database

import (
	"context"
)

const deleteTagByName = `-- name: DeleteTagByName :exec
DELETE FROM tags
WHERE name = $1
`

func (q *Queries) DeleteTagByName(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteTagByName, name)
	return err
}
