// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: delete_all_requests.sql

package database

import (
	"context"
)

const deleteAllRequests = `-- name: DeleteAllRequests :exec
DELETE FROM requests
`

func (q *Queries) DeleteAllRequests(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllRequests)
	return err
}
