// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: does_tag_exist.sql

package database

import (
	"context"
)

const doesTagExist = `-- name: DoesTagExist :one
SELECT COUNT(*)
FROM tags
WHERE name = $1
`

func (q *Queries) DoesTagExist(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, doesTagExist, name)
	var count int64
	err := row.Scan(&count)
	return count, err
}
