// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: does_tag_alias_exist.sql

package database

import (
	"context"
)

const doesTagAliasExist = `-- name: DoesTagAliasExist :one
SELECT COUNT(*)
FROM tag_aliases
WHERE name = $1
`

func (q *Queries) DoesTagAliasExist(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, doesTagAliasExist, name)
	var count int64
	err := row.Scan(&count)
	return count, err
}
