// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_requests_from_tags_and_text.sql

package database

import (
	"context"

	"github.com/lib/pq"
)

const getRequestsFromTagsAndText = `-- name: GetRequestsFromTagsAndText :many
SELECT id, created_at, updated_at, request_text, status, request_search_vector
FROM requests
WHERE $1::text[] <@ (
    SELECT coalesce(array_agg(tags.name), '{}')
    FROM request_tags
    LEFT JOIN tags ON tags.id = request_tags.tag_id
    WHERE requests.id = request_tags.request_id
) AND request_search_vector @@ websearch_to_tsquery('english', $2)
ORDER BY ts_rank(request_search_vector, websearch_to_tsquery('english', $2)) DESC
LIMIT 10
`

type GetRequestsFromTagsAndTextParams struct {
	Column1            []string
	WebsearchToTsquery string
}

func (q *Queries) GetRequestsFromTagsAndText(ctx context.Context, arg GetRequestsFromTagsAndTextParams) ([]Request, error) {
	rows, err := q.db.QueryContext(ctx, getRequestsFromTagsAndText, pq.Array(arg.Column1), arg.WebsearchToTsquery)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Request
	for rows.Next() {
		var i Request
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RequestText,
			&i.Status,
			&i.RequestSearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
