// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_tag_autocomplete_list.sql

package database

import (
	"context"
	"database/sql"
)

const getTagAutocompleteList = `-- name: GetTagAutocompleteList :many
SELECT name
FROM tags
WHERE name LIKE $1 || '%'

UNION

SELECT name
FROM tags
WHERE name % $1


ORDER BY post_count DESC
LIMIT 5
`

func (q *Queries) GetTagAutocompleteList(ctx context.Context, dollar_1 sql.NullString) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getTagAutocompleteList, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
