// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_tag_by_id.sql

package database

import (
	"context"
)

const getTagByID = `-- name: GetTagByID :one
SELECT id, name, post_count, created_at, updated_at
FROM tags
WHERE id = $1
`

func (q *Queries) GetTagByID(ctx context.Context, id int64) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTagByID, id)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PostCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
