// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_single_request.sql

package database

import (
	"context"
)

const getSingleRequest = `-- name: GetSingleRequest :one
SELECT id, created_at, updated_at, request_text, status, request_search_vector FROM requests
WHERE id = $1
`

func (q *Queries) GetSingleRequest(ctx context.Context, id int64) (Request, error) {
	row := q.db.QueryRowContext(ctx, getSingleRequest, id)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RequestText,
		&i.Status,
		&i.RequestSearchVector,
	)
	return i, err
}
