// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_first_page_cursor.sql

package database

import (
	"context"
)

const getFirstPageCursor = `-- name: GetFirstPageCursor :one
SELECT id FROM requests ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetFirstPageCursor(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getFirstPageCursor)
	var id int64
	err := row.Scan(&id)
	return id, err
}
