// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_tag_links_for_request.sql

package database

import (
	"context"
	"time"
)

const getTagLinksForRequest = `-- name: GetTagLinksForRequest :many
SELECT id, name, post_count, created_at, updated_at, request_id, tag_id
FROM tags
JOIN request_tags ON tags.id = request_tags.tag_id
WHERE request_tags.request_id = $1
`

type GetTagLinksForRequestRow struct {
	ID        int64
	Name      string
	PostCount int32
	CreatedAt time.Time
	UpdatedAt time.Time
	RequestID int64
	TagID     int64
}

func (q *Queries) GetTagLinksForRequest(ctx context.Context, requestID int64) ([]GetTagLinksForRequestRow, error) {
	rows, err := q.db.QueryContext(ctx, getTagLinksForRequest, requestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTagLinksForRequestRow
	for rows.Next() {
		var i GetTagLinksForRequestRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PostCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RequestID,
			&i.TagID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
