// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_tag_autocomplete_list.sql

package database

import (
	"context"
	"database/sql"
)

const getTagAutocompleteList = `-- name: GetTagAutocompleteList :many
SELECT id, name, post_count, created_at, updated_at
FROM tags
WHERE name LIKE $1 || '%'

UNION

SELECT id, name, post_count, created_at, updated_at
FROM tags
WHERE name % $1


ORDER BY post_count DESC
LIMIT 10
`

func (q *Queries) GetTagAutocompleteList(ctx context.Context, dollar_1 sql.NullString) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, getTagAutocompleteList, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PostCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
