// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_request_claims.sql

package database

import (
	"context"
)

const getRequestClaims = `-- name: GetRequestClaims :many
SELECT request_id, claimed_at, claim_secret_hash, expires_at FROM request_claims
WHERE expires_at IS NOT NULL
AND request_id <= $1
ORDER BY claimed_at DESC
LIMIT 5
`

func (q *Queries) GetRequestClaims(ctx context.Context, requestID int64) ([]RequestClaim, error) {
	rows, err := q.db.QueryContext(ctx, getRequestClaims, requestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RequestClaim
	for rows.Next() {
		var i RequestClaim
		if err := rows.Scan(
			&i.RequestID,
			&i.ClaimedAt,
			&i.ClaimSecretHash,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
