// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_all_requests_filtered.sql

package database

import (
	"context"
)

const getAllRequestsFiltered = `-- name: GetAllRequestsFiltered :many
SELECT id, created_at, updated_at, request_text, status FROM requests
WHERE status = $1
`

func (q *Queries) GetAllRequestsFiltered(ctx context.Context, status RequestStatus) ([]Request, error) {
	rows, err := q.db.QueryContext(ctx, getAllRequestsFiltered, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Request
	for rows.Next() {
		var i Request
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RequestText,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
