// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_request_count.sql

package database

import (
	"context"
)

const getRequestCount = `-- name: GetRequestCount :one
SELECT COUNT(*) FROM requests
`

func (q *Queries) GetRequestCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getRequestCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}
