// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_tag_id_from_alias.sql

package database

import (
	"context"
	"database/sql"
)

const getTagIdFromAlias = `-- name: GetTagIdFromAlias :one
SELECT tag_id
FROM tag_aliases
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetTagIdFromAlias(ctx context.Context, id int64) (sql.NullInt64, error) {
	row := q.db.QueryRowContext(ctx, getTagIdFromAlias, id)
	var tag_id sql.NullInt64
	err := row.Scan(&tag_id)
	return tag_id, err
}
