// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_requests_from_tags.sql

package database

import (
	"context"
)

const getRequestsFromTags = `-- name: GetRequestsFromTags :many
SELECT id, created_at, updated_at, request_text, status, request_search_vector
FROM requests
WHERE $1 <@ (
    SELECT coalesce(array_agg(tags.name), '{}')
    FROM request_tags
    LEFT JOIN tags ON tags.id = request_tags.tag_id
    WHERE requests.id = request_tags.request_id
)
LIMIT 10
`

func (q *Queries) GetRequestsFromTags(ctx context.Context, name string) ([]Request, error) {
	rows, err := q.db.QueryContext(ctx, getRequestsFromTags, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Request
	for rows.Next() {
		var i Request
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RequestText,
			&i.Status,
			&i.RequestSearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
