// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_next_request_page.sql

package database

import (
	"context"
)

const getNextRequestPage = `-- name: GetNextRequestPage :many
SELECT id, created_at, updated_at, request_text, status, request_search_vector FROM requests
WHERE status = $1
AND id <= $2
ORDER BY created_at DESC
LIMIT 5
`

type GetNextRequestPageParams struct {
	Status RequestStatus
	ID     int64
}

func (q *Queries) GetNextRequestPage(ctx context.Context, arg GetNextRequestPageParams) ([]Request, error) {
	rows, err := q.db.QueryContext(ctx, getNextRequestPage, arg.Status, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Request
	for rows.Next() {
		var i Request
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RequestText,
			&i.Status,
			&i.RequestSearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
