// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"
)

type Request struct {
	ID          int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
	RequestText string
}

type RequestClaim struct {
	RequestID       int64
	ClaimedAt       time.Time
	ClaimSecretHash string
	ExpiresAt       time.Time
}
